# Generated by Django 5.0.3 on 2024-03-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(null=True),
        ),
    ]
